# 切分、拆分、分割


和级联类似，基本上只用到三个函数：

- np.split
- np.hsplit
- np.vsplit


In [6]:
import numpy as np


In [7]:
n = np.random.randint(0, 100, size=(6, 4))
n

array([[10, 12, 96,  2],
       [10, 82, 45, 62],
       [83, 74, 97, 75],
       [93, 62, 43, 32],
       [61, 37, 80, 63],
       [77, 78, 91, 65]])

In [10]:
li_n = np.vsplit(n, 3)  # 垂直方向拆成三份
li_n

[array([[10, 12, 96,  2],
        [10, 82, 45, 62]]),
 array([[83, 74, 97, 75],
        [93, 62, 43, 32]]),
 array([[61, 37, 80, 63],
        [77, 78, 91, 65]])]

In [11]:
# 指定拆分位置
np.vsplit(n, (1,2,4))

[array([[10, 12, 96,  2]]),
 array([[10, 82, 45, 62]]),
 array([[83, 74, 97, 75],
        [93, 62, 43, 32]]),
 array([[61, 37, 80, 63],
        [77, 78, 91, 65]])]

: 