# 级联


np.concatenate()

- 参数是列表或者元组
- 级联的数组维度必须相同
- 可以通过axis参数改变级联的方向


In [1]:
import numpy as np

In [3]:
n1 = np.random.randint(0, 100, size=(3, 5))
n2 = np.random.randint(0, 100, size=(3, 5))

print(f"n1:{n1}")
print(f"n2:{n2}")

n1:[[29  4 27  2 65]
 [58 41 21 78 81]
 [65 79 96 18 11]]
n2:[[67 68 31 38 89]
 [86 54 86 52 75]
 [52 94 24 99 66]]


In [4]:
# 级联合并
np.concatenate((n1,n2))

array([[29,  4, 27,  2, 65],
       [58, 41, 21, 78, 81],
       [65, 79, 96, 18, 11],
       [67, 68, 31, 38, 89],
       [86, 54, 86, 52, 75],
       [52, 94, 24, 99, 66]])

可以看出，默认情况下是上下合并/级联的。


In [5]:
# 水平方向级联合并
np.concatenate(
    (n1, n2), axis=0
)  # axis=0表示第一个维度，也就是行，所以是在行的角度进行合并。

array([[29,  4, 27,  2, 65],
       [58, 41, 21, 78, 81],
       [65, 79, 96, 18, 11],
       [67, 68, 31, 38, 89],
       [86, 54, 86, 52, 75],
       [52, 94, 24, 99, 66]])

In [6]:
# 水平方向级联合并
np.concatenate(
    (n1, n2), axis=1
)  # axis=1表示第二个维度，也就是列

array([[29,  4, 27,  2, 65, 67, 68, 31, 38, 89],
       [58, 41, 21, 78, 81, 86, 54, 86, 52, 75],
       [65, 79, 96, 18, 11, 52, 94, 24, 99, 66]])

此外，使用`np.hstack`和`np.vstack()`也可以实现级联合并效果，用法一样，此处不做赘述。