# numpy数组变形


使用reshape函数可以对数组进行变形。


In [7]:
import numpy as np

In [8]:
n = np.arange(1,21)
n

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

使用reshape修改形状。

In [9]:
n.shape  # 原形状

(20,)

In [10]:
# 变成二维
n1 = np.reshape(n, (4,5))  # 将二十个元素变成4x5的数组

In [13]:
print(n1)
n1.shape  # 做个检查

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


(4, 5)

In [14]:
# 换个写法
n1.reshape(5,4)  # 换成五行四列

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [15]:
# 不能换成五行五列，因为元素数量不同
n1.reshape(5,5)

ValueError: cannot reshape array of size 20 into shape (5,5)

In [18]:
# 还原成一维数组
n1.reshape(20)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

函数中的`-1`参数表示任意剩余的维度长度

In [19]:
n1.reshape(4,-1)  # 当第一个维度写好后，使用`-1`会自动判断后面的维度。

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])