# NumPy笔记ep04-NumPy基本操作

NumPy基本操作包括：索引、切片两个。


## 1. 索引操作

一维索引与列表完全一致，多维索引同理。


In [2]:
import numpy as np

In [4]:

l = [1, 2, 3, 4, 5]

n = np.array(l)

n[0], n[-1]

(1, 5)

In [6]:
# 产生一个随机的二维数组
n = np.random.randint(0, 10, size=(4,5))

n

array([[8, 4, 1, 7, 5],
       [0, 3, 5, 3, 6],
       [1, 4, 7, 9, 8],
       [0, 2, 1, 8, 8]])

In [9]:
print(n[3][4])  # 最后一个数
print(n[-1][-1])  # 换一种写法

# 上面的写法可以简化为下面的样子：
print(n[3, 4])
print(n[-1, -1])

8
8
8
8


对于三维数组的操作，与上面二维类似，这里不再赘述。

## 2. 切片操作


In [11]:
l = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

# Python列表的切片
l[2:6]  # 会输出下标2到5的元素（左闭右开

[3, 4, 5, 6]

In [12]:
# Python列表切片
l[::-1]  # 反转输出l

[10, 9, 8, 7, 6, 5, 4, 3, 2, 1]

NumPy中的ndarray数组的切片和list类似。


In [13]:
n = np.array(l)

n

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [15]:
n[2:6], n[::-1]

(array([3, 4, 5, 6]), array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1]))

In [19]:
n = np.random.randint(0, 50, size=(6,8))  # 六行八列的随机数数组

n

array([[20, 26, 35, 46,  7, 47,  5, 30],
       [17, 33, 21, 13, 28, 11, 36,  4],
       [33, 11, 49, 18, 14, 38, 44, 40],
       [46,  0, 28, 13, 38,  3, 15, 35],
       [24, 45,  4, 41, 23, 11, 21, 13],
       [32, 19, 13,  2,  6, 45, 40, 21]])

In [28]:
# 取一行数据
print(f"第三行数据:{n[2]}")

# 连续取多行（切片
print(f"第2-4行：{n[1:4]}")

# 取不连续的多行
print(f'取第2、3、3、5行：{n[ [1,2,2,4] ]}')


第三行数据:[33 11 49 18 14 38 44 40]
第2-4行：[[17 33 21 13 28 11 36  4]
 [33 11 49 18 14 38 44 40]
 [46  0 28 13 38  3 15 35]]
取第2、3、5行：[[17 33 21 13 28 11 36  4]
 [33 11 49 18 14 38 44 40]
 [33 11 49 18 14 38 44 40]
 [24 45  4 41 23 11 21 13]]


取列的操作会略有区别。

In [ ]:
# 取一列
print(f'n[0]')

# 取连续多列

# 取不连续的多列